# Generated by Django 4.1.7 on 2023-05-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
